//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkladUchetEntities : DbContext
    {
        public SkladUchetEntities()
            : base("name=SkladUchetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ЕдиницыИзмерения> ЕдиницыИзмерения { get; set; }
        public virtual DbSet<ЗоныХранения> ЗоныХранения { get; set; }
        public virtual DbSet<Инвентаризации> Инвентаризации { get; set; }
        public virtual DbSet<КатегорииТоваров> КатегорииТоваров { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<ПриходныеНакладные> ПриходныеНакладные { get; set; }
        public virtual DbSet<РасходныеНакладные> РасходныеНакладные { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Склады> Склады { get; set; }
        public virtual DbSet<СтрокиИнвентаризации> СтрокиИнвентаризации { get; set; }
        public virtual DbSet<СтрокиПриходнойНакладной> СтрокиПриходнойНакладной { get; set; }
        public virtual DbSet<СтрокиРасходнойНакладной> СтрокиРасходнойНакладной { get; set; }
        public virtual DbSet<ТипыСкладов> ТипыСкладов { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
        public virtual DbSet<ТоварыНаСкладе> ТоварыНаСкладе { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<CustomerOrderItem> CustomerOrderItems { get; set; }
        public virtual DbSet<CustomerOrder> CustomerOrders { get; set; }
    }
}
