//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.Инвентаризации = new HashSet<Инвентаризации>();
        }
    
        public int User_ID { get; set; }
        public string Имя_Пользователя { get; set; }
        public string Хеш_Пароля { get; set; }
        public string Соль { get; set; }
        public int Role_ID { get; set; }
        public string Электронная_Почта { get; set; }
        public Nullable<bool> Двухфакторная_Аутентификация_Включена { get; set; }
        public string Секрет_Двухфакторной_Аутентификации { get; set; }
        public byte[] Фотография { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Инвентаризации> Инвентаризации { get; set; }
        public virtual Роли Роли { get; set; }
    }
}
