//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class РасходныеНакладные
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public РасходныеНакладные()
        {
            this.СтрокиРасходнойНакладной = new HashSet<СтрокиРасходнойНакладной>();
        }
    
        public int Invoice_ID { get; set; }
        public string Номер_Накладной { get; set; }
        public System.DateTime Дата_Накладной { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<decimal> Сумма_Накладной { get; set; }
        public byte[] Файл { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтрокиРасходнойНакладной> СтрокиРасходнойНакладной { get; set; }
    }
}
