//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Склады
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Склады()
        {
            this.ЗоныХранения = new HashSet<ЗоныХранения>();
            this.ТоварыНаСкладе = new HashSet<ТоварыНаСкладе>();
        }
    
        public int Warehouse_ID { get; set; }
        public string Название_Склада { get; set; }
        public string Адрес { get; set; }
        public int Warehouse_Type_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗоныХранения> ЗоныХранения { get; set; }
        public virtual ТипыСкладов ТипыСкладов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТоварыНаСкладе> ТоварыНаСкладе { get; set; }
    }
}
