//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class СтрокиПриходнойНакладной
    {
        public int Invoice_Item_ID { get; set; }
        public int Invoice_ID { get; set; }
        public int Product_ID { get; set; }
        public int Количество { get; set; }
        public decimal Цена { get; set; }
    
        public virtual ПриходныеНакладные ПриходныеНакладные { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
