//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class СтрокиИнвентаризации
    {
        public int Inventory_Item_ID { get; set; }
        public int Inventory_ID { get; set; }
        public int Product_ID { get; set; }
        public int Фактическое_Количество { get; set; }
        public int Учетное_Количество { get; set; }
    
        public virtual Инвентаризации Инвентаризации { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
