//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТоварыНаСкладе
    {
        public int Warehouse_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Storage_Location_ID { get; set; }
        public int Количество { get; set; }
    
        public virtual ЗоныХранения ЗоныХранения { get; set; }
        public virtual Склады Склады { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
