//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.СтрокиИнвентаризации = new HashSet<СтрокиИнвентаризации>();
            this.СтрокиПриходнойНакладной = new HashSet<СтрокиПриходнойНакладной>();
            this.СтрокиРасходнойНакладной = new HashSet<СтрокиРасходнойНакладной>();
            this.ТоварыНаСкладе = new HashSet<ТоварыНаСкладе>();
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItem>();
            this.CustomerOrderItems = new HashSet<CustomerOrderItem>();
        }
    
        public int Product_ID { get; set; }
        public string Название_Товара { get; set; }
        public string Артикул { get; set; }
        public string Штрихкод { get; set; }
        public int Category_ID { get; set; }
        public int Unit_ID { get; set; }
        public decimal Цена { get; set; }
        public string Серийный_Номер { get; set; }
        public Nullable<int> Минимальный_Остаток { get; set; }
        public Nullable<System.DateTime> Срок_Годности { get; set; }
        public byte[] Изображение { get; set; }
    
        public virtual ЕдиницыИзмерения ЕдиницыИзмерения { get; set; }
        public virtual КатегорииТоваров КатегорииТоваров { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтрокиИнвентаризации> СтрокиИнвентаризации { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтрокиПриходнойНакладной> СтрокиПриходнойНакладной { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СтрокиРасходнойНакладной> СтрокиРасходнойНакладной { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТоварыНаСкладе> ТоварыНаСкладе { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrderItem> CustomerOrderItems { get; set; }
    }
}
